<?php

namespace SmartKeyTurkey\Core;

defined( 'ABSPATH' ) || exit;

final class Editorial {
	private const VERSION = '1.1.0';
	public static function init(): void { add_action( 'init', array( self::class, 'seed' ), 52 ); add_action( 'add_meta_boxes_post', array( self::class, 'meta_box' ) ); add_action( 'save_post_post', array( self::class, 'save' ) ); add_action( 'wp_enqueue_scripts', array( self::class, 'assets' ) ); add_filter( 'template_include', array( self::class, 'template' ), 106 ); add_filter( 'rank_math/frontend/title', array( self::class, 'archive_title' ) ); add_filter( 'rank_math/frontend/description', array( self::class, 'archive_description' ) ); }
	public static function meta_box(): void { add_meta_box( 'skt_editorial_source', 'Source and editorial review', array( self::class, 'render_meta_box' ), 'post', 'normal', 'high' ); }
	public static function render_meta_box( \WP_Post $post ): void { wp_nonce_field( 'skt_editorial_save', 'skt_editorial_nonce' ); $fields = array( 'skt_source_url' => 'Primary source URL', 'skt_source_name' => 'Source name', 'skt_reviewed_date' => 'Last reviewed (YYYY-MM-DD)', 'skt_editorial_status' => 'Editorial status' ); echo '<table class="form-table"><tbody>'; foreach ( $fields as $key => $label ) { echo '<tr><th><label for="' . esc_attr( $key ) . '">' . esc_html( $label ) . '</label></th><td><input class="regular-text" id="' . esc_attr( $key ) . '" name="' . esc_attr( $key ) . '" value="' . esc_attr( (string) get_post_meta( $post->ID, $key, true ) ) . '"></td></tr>'; } echo '</tbody></table><p><small>AI-assisted English content remains pending human editorial review until explicitly approved.</small></p>'; }
	public static function save( int $post_id ): void { if ( ! isset( $_POST['skt_editorial_nonce'] ) || ! wp_verify_nonce( sanitize_text_field( wp_unslash( $_POST['skt_editorial_nonce'] ) ), 'skt_editorial_save' ) || ! current_user_can( 'edit_post', $post_id ) ) { return; } foreach ( array( 'skt_source_url', 'skt_source_name', 'skt_reviewed_date', 'skt_editorial_status' ) as $key ) { if ( isset( $_POST[ $key ] ) ) { update_post_meta( $post_id, $key, 'skt_source_url' === $key ? esc_url_raw( wp_unslash( $_POST[ $key ] ) ) : sanitize_text_field( wp_unslash( $_POST[ $key ] ) ) ); } } }
	public static function seed(): void {
		if ( self::VERSION === get_option( 'skt_editorial_version' ) ) { return; }
		$lock = (int) get_option( 'skt_editorial_seed_lock', 0 );
		if ( $lock && time() - $lock < 300 ) { return; }
		if ( $lock ) { delete_option( 'skt_editorial_seed_lock' ); }
		if ( ! add_option( 'skt_editorial_seed_lock', time(), '', false ) ) { return; }
		$categories = array( 'Market News' => 'market-news', 'Laws & Guidance' => 'laws-guidance', 'Events' => 'events' ); $term_ids = array();
		foreach ( $categories as $name => $slug ) { $term = term_exists( $slug, 'category' ); if ( $term ) { $term_ids[ $slug ] = (int) ( is_array( $term ) ? $term['term_id'] : $term ); } else { $created = wp_insert_term( $name, 'category', array( 'slug' => $slug ) ); if ( ! is_wp_error( $created ) ) { $term_ids[ $slug ] = (int) $created['term_id']; } } }
		$records = array(
			array( 'slug' => 'turkiye-house-sales-june-2026', 'category' => 'market-news', 'title' => 'Türkiye House Sales Rose 15.8% in June 2026: What the Official Data Shows', 'excerpt' => 'Türkiye recorded 129,979 house sales in June 2026, while sales to foreign buyers reached 2,015, according to the latest official release.', 'source' => 'https://veriportali.tuik.gov.tr/tr/press/58344', 'source_name' => 'Turkish Statistical Institute (TURKSTAT)', 'content' => '<p>Türkiye recorded <strong>129,979 house sales in June 2026</strong>, an increase of 15.8% compared with June 2025, according to the Turkish Statistical Institute. The monthly total included 43,406 first-hand sales and 86,573 existing-home sales.</p><h2>Foreign-buyer activity increased in June</h2><p>Sales to foreign buyers reached 2,015 in June, up 20.1% year over year, and represented 1.6% of all house sales. However, the January–June total was 9,083, which was 9.2% lower than the same period of 2025.</p><h2>How buyers should read the figures</h2><p>National transaction data describes the market as a whole; it does not establish the availability, legal status or value of a specific property. Buyers should still verify title records, restrictions, debts, project documents and current transaction terms for the selected asset.</p><p>SmartKeyTurkey publishes property prices and commercial terms only in response to a qualified request.</p>' ),
			array( 'slug' => 'international-composite-exhibition-turkiye-2026', 'category' => 'events', 'title' => 'International Composite Exhibition Türkiye 2026: A Planning Note for Industrial Buyers', 'excerpt' => 'Türkiye’s official investment portal lists the International Composite Exhibition for 21 October 2026, creating a useful planning point for materials buyers.', 'source' => 'https://www.invest.gov.tr/en/Pages/home-page.aspx?lng=en', 'source_name' => 'Investment and Finance Office of the Presidency of the Republic of Türkiye', 'content' => '<p>The official Invest in Türkiye events calendar lists the <strong>International Composite Exhibition</strong> for 21 October 2026. For industrial buyers, composite-sector events can provide a practical setting to compare materials, applications and supplier capabilities.</p><h2>Prepare a useful sourcing brief</h2><p>Before attending or arranging meetings, document the required polymer or material family, grade, application, volume, packaging, destination, compliance documents and delivery target. This makes supplier conversations more focused and easier to compare.</p><h2>Confirm current event details</h2><p>Venue, programme, registration and exhibitor information may change. Check the organizer and the official investment portal before making travel or commercial commitments.</p>' ),
			array( 'slug' => 'turkiye-algeria-polypropylene-project-2026', 'category' => 'market-news', 'title' => 'Türkiye–Algeria Polypropylene Project: What the 2026 Ceyhan Announcement Means', 'excerpt' => 'Türkiye’s Ministry of Trade highlighted a planned polypropylene production facility and terminal in Ceyhan during the Türkiye–Algeria Business Forum in May 2026.', 'source' => 'https://ticaret.gov.tr/haberler/turkiye-cezayir-is-forumu-ankarada-gerceklestirildi', 'source_name' => 'Republic of Türkiye Ministry of Trade', 'content' => '<p>At the Türkiye–Algeria Business Forum held in Ankara on 7 May 2026, Türkiye’s Ministry of Trade highlighted a planned <strong>polypropylene production facility and terminal project in Ceyhan</strong>. The ministry described the project as an investment expected to contribute to Türkiye’s petrochemical production capacity.</p><h2>Why this matters to industrial buyers</h2><p>Additional domestic production capacity can influence the future sourcing landscape, but an announced project does not by itself confirm grade availability, production schedules, allocations or commercial terms. Buyers should continue to qualify every offer against the required specification, application, documentation, packaging and delivery destination.</p><h2>Trade discussions remain part of the context</h2><p>The official forum report also referenced ongoing discussions concerning a preferential trade agreement and investment protection. These discussions should not be treated as completed arrangements until the relevant authorities publish final, effective terms.</p><p>SmartKeyTurkey provides product availability and commercial terms only after reviewing a qualified request.</p>' ),
			array( 'slug' => 'cop31-turkiye-2026-industrial-sustainability-planning', 'category' => 'events', 'title' => 'COP31 Türkiye 2026: A Planning Note for Industrial and Property Businesses', 'excerpt' => 'Türkiye’s official investment portal lists COP31 Türkiye for 9 November 2026, giving businesses a timely checkpoint for sustainability planning.', 'source' => 'https://www.invest.gov.tr/en/Pages/home-page.aspx?lng=en', 'source_name' => 'Investment and Finance Office of the Presidency of the Republic of Türkiye', 'content' => '<p>The official Invest in Türkiye events calendar lists <strong>COP31 Türkiye</strong> for 9 November 2026. For industrial suppliers, property operators and business buyers, the event horizon is a useful prompt to review the quality of sustainability data used in commercial decisions.</p><h2>What businesses can prepare now</h2><p>Teams can identify which energy, materials, logistics, emissions and building-performance information is already documented, where evidence is incomplete, and which claims require independent verification. Petrochemical buyers can also confirm whether requested technical and compliance documents match the intended market and application.</p><h2>Use confirmed information</h2><p>Programmes, venues, participation requirements and related announcements can change. Businesses should verify the latest details with the official event organizers and public authorities before making travel, investment or compliance decisions.</p><p>This planning note does not state that new legal duties have taken effect; it is a practical readiness checklist based on the official event listing.</p>' ),
		);
		global $wpdb;
		foreach ( $records as $record ) { if ( empty( $term_ids[ $record['category'] ] ) ) { continue; } $existing_id = (int) $wpdb->get_var( $wpdb->prepare( "SELECT ID FROM {$wpdb->posts} WHERE post_type = 'post' AND post_name = %s AND post_status != 'trash' ORDER BY ID ASC LIMIT 1", $record['slug'] ) ); $post_id = $existing_id ?: (int) wp_insert_post( array( 'post_type' => 'post', 'post_status' => 'publish', 'post_name' => $record['slug'], 'post_title' => $record['title'], 'post_excerpt' => $record['excerpt'], 'post_content' => $record['content'], 'post_category' => array( $term_ids[ $record['category'] ] ) ) ); if ( ! $post_id ) { continue; } wp_set_post_categories( $post_id, array( $term_ids[ $record['category'] ] ), false ); update_post_meta( $post_id, 'skt_source_url', $record['source'] ); update_post_meta( $post_id, 'skt_source_name', $record['source_name'] ); update_post_meta( $post_id, 'skt_reviewed_date', '2026-07-21' ); update_post_meta( $post_id, 'skt_editorial_status', 'AI-assisted draft — pending human review' ); update_post_meta( $post_id, 'rank_math_description', $record['excerpt'] ); }
		if ( ! empty( $term_ids['laws-guidance'] ) ) { $existing = get_posts( array( 'post_type' => 'post', 'post_status' => 'publish', 'posts_per_page' => -1, 'fields' => 'ids', 's' => 'property' ) ); foreach ( $existing as $post_id ) { if ( ! has_category( array( 'market-news', 'events' ), $post_id ) ) { wp_set_post_categories( $post_id, array( $term_ids['laws-guidance'] ), true ); } } }
		update_option( 'skt_editorial_version', self::VERSION, false );
		delete_option( 'skt_editorial_seed_lock' );
	}
	public static function assets(): void { if ( is_home() || is_category() || is_singular( 'post' ) ) { wp_enqueue_style( 'smartkey-editorial', plugins_url( 'assets/css/editorial.css', SKT_CORE_FILE ), array( 'smartkey-design-tokens' ), SKT_CORE_VERSION ); } }
	public static function template( string $template ): string { if ( is_home() || is_category() ) { return SKT_CORE_DIR . 'templates/editorial-archive.php'; } if ( is_singular( 'post' ) ) { return SKT_CORE_DIR . 'templates/editorial-single.php'; } return $template; }
	public static function archive_title( string $title ): string { return is_home() ? 'Turkey News, Laws & Events | SmartKeyTurkey' : $title; }
	public static function archive_description( string $description ): string { return is_home() ? 'Read sourced English updates on Turkey property, regulations, business events and market developments from SmartKeyTurkey.' : $description; }
	public static function archive(): string { $cats = get_categories( array( 'slug' => array( 'market-news', 'laws-guidance', 'events' ) ) ); ob_start(); ?><main class="skt-editorial" id="main-content"><section class="skt-editorial-hero"><div class="skt-editorial-shell"><p class="skt-editorial-eyebrow">News & Insights</p><h1><?php echo is_category() ? esc_html( single_cat_title( '', false ) ) : 'Turkey news, laws and events—made easier to follow.'; ?></h1><p>Sourced English updates for property audiences and business buyers, with visible source and review information.</p></div></section><nav class="skt-editorial-categories skt-editorial-shell" aria-label="Editorial categories"><a href="<?php echo esc_url( home_url( '/blog/' ) ); ?>"<?php echo is_category() ? '' : ' aria-current="page"'; ?>>All insights</a><?php foreach ( $cats as $cat ) : ?><a href="<?php echo esc_url( get_category_link( $cat ) ); ?>"<?php echo is_category( $cat->term_id ) ? ' aria-current="page"' : ''; ?>><?php echo esc_html( $cat->name ); ?></a><?php endforeach; ?></nav><section class="skt-editorial-shell skt-editorial-results"><div class="skt-editorial-grid"><?php while ( have_posts() ) : the_post(); $cat = get_the_category(); ?><article><a class="skt-editorial-media" href="<?php the_permalink(); ?>"><span><?php echo esc_html( $cat ? $cat[0]->name : 'Insight' ); ?></span><b aria-hidden="true">SK</b></a><div><p><?php echo esc_html( get_the_date( 'F j, Y' ) ); ?></p><h2><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h2><p><?php echo esc_html( get_the_excerpt() ); ?></p><a href="<?php the_permalink(); ?>">Read insight →</a></div></article><?php endwhile; ?></div><nav class="skt-editorial-pagination" aria-label="Insight pages"><?php echo wp_kses_post( paginate_links( array( 'type' => 'list' ) ) ); ?></nav></section></main><?php return (string) ob_get_clean(); }
	public static function single(): string { $post_id = get_queried_object_id(); $source = (string) get_post_meta( $post_id, 'skt_source_url', true ); $source_name = (string) get_post_meta( $post_id, 'skt_source_name', true ); $reviewed = (string) get_post_meta( $post_id, 'skt_reviewed_date', true ); $status = (string) get_post_meta( $post_id, 'skt_editorial_status', true ); $cat = get_the_category( $post_id ); ob_start(); ?><main class="skt-editorial-single" id="main-content"><section class="skt-editorial-hero"><div class="skt-editorial-shell"><p class="skt-editorial-eyebrow"><?php echo esc_html( $cat ? $cat[0]->name : 'Insight' ); ?></p><h1><?php the_title(); ?></h1><p><?php echo esc_html( get_the_excerpt() ); ?></p><div class="skt-editorial-byline"><span><?php echo esc_html( get_the_date( 'F j, Y' ) ); ?></span><?php if ( $reviewed ) : ?><span>Reviewed <?php echo esc_html( $reviewed ); ?></span><?php endif; ?></div></div></section><div class="skt-editorial-shell skt-editorial-article"><article><?php the_content(); ?><div class="skt-editorial-disclaimer"><strong>Editorial note</strong><p>This information is general and does not replace legal, tax, technical or investment advice. Verify current requirements for your specific transaction.</p></div></article><aside><h2>Source & review</h2><?php if ( $source_name ) : ?><p><strong>Primary source</strong><br><?php echo esc_html( $source_name ); ?></p><?php endif; ?><?php if ( $source ) : ?><a href="<?php echo esc_url( $source ); ?>" target="_blank" rel="noopener noreferrer">Open official source ↗</a><?php endif; ?><?php if ( $status ) : ?><p class="skt-editorial-status"><?php echo esc_html( $status ); ?></p><?php endif; ?></aside></div></main><?php return (string) ob_get_clean(); }
}
